[package]
name = "modiom"
version = "0.1.0"
description = "command line tool for mod.io"
readme = "README.md"
repository = "https://github.com/nickelc/modiom"
license = "MIT/Apache-2.0"
authors = ["Constantin Nickel <constantin.nickel@gmail.com>"]
keywords = ["modio", "cli"]
categories = ["command-line-utilities"]
edition = "2018"

[[bin]]
name = "modiom"

[dependencies]
bytes = "0.5"
clap = "2"
dirs = "2"
futures = "0.3"
lazycell = "1"
md-5 = "0.8"
nom = "5"
pbr = "1"
serde = { version = "1", features = ["derive"] }
textwrap = "0.11"
tokio = "0.2"
tokio-util = { version = "0.3", features = ["codec"] }
toml = "0.5"

[dependencies.modio]
version = "0.4"
git = "https://github.com/nickelc/modio-rs.git"

[dependencies.cfg]
package = "config"
version = "0.9"
default-features = false
features = ["toml"]

[dependencies.prettytable-rs]
version = "0.8"
default-features = false
